### ISSUE TITLE
[1.12.2] java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by codetaylor** [oneandonlyflexo/barkbooks#2]
Forge: 14.23.1.2562
MC: 1.12.2
Bark Books: 1.12.2-1.0
Nibbler: 1.12.2-0.2

```
Caused by: java.lang.NoClassDefFoundError: one/flexo/nibbler/registry/NibblerRegistry
	at one.flexo.nibbler.Nibbler.<clinit>(Nibbler.java:46)
	...
```

Full crash log:
https://gist.github.com/codetaylor/0458f82807b9a3875a0e54216918053c

**Comment by oneandonlyflexo** [comment]
Yeah. I'm not having much luck figuring it out in afraid.

**Comment by codetaylor** [comment]
Does it work ok in your dev environment?

**Comment by codetaylor** [comment]
If I remove Bark Books and leave Nibbler, everything loads fine.

**Comment by oneandonlyflexo** [comment]
Yeah it all works fine in my dev environment asks I also noticed that it is bark books that breaks it. Not sure why.

**Comment by oneandonlyflexo** [comment]
Bark Books 1.1 fixes this issue (by removing the dependency on Nibbler and just putting all of its relevant code directly in bark books).  I'm creating a separate issue to figure out what the issue is with the Bark Books/Nibbler interaction that was causing this crash.
